# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_mapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapper',
            name='original_url',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
